# Generated by Django 4.2.3 on 2023-07-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='professor',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='professor',
            field=models.ManyToManyField(blank=True, to='students.professordata'),
        ),
    ]
