# Generated by Django 4.2.3 on 2023-07-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_professordata_remove_studentdata_professor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='professor',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.professordata'),
        ),
    ]
