# Generated by Django 4.2.3 on 2023-08-06 14:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_statusdata_universitydata_alter_studentdata_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='age',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.professordata'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.statusdata'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.universitydata'),
        ),
    ]
