# Generated by Django 4.2.3 on 2023-08-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_delete_studentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='name',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
